version: '3.8'

services:
  db_test:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_test
    ports:
      - "5433:5432"

  web_test:
    build: .
    command: bash -c "bundle exec rails db:create db:migrate RAILS_ENV=test && bundle exec rspec"
    volumes:
      - .:/app
    depends_on:
      - db_test
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db_test:5432/tasks_test
      RAILS_ENV: test

